{% set version = "1.5.0" %}

package:
  name: cis
  version: {{ version }}

source:
  fn: cis-{{ version }}.tar.gz
  url: https://github.com/cedadev/cis/archive/{{ version }}.tar.gz
  sha256: 215221db1b93a3b1d79f495aebc2096aec937c9f052328feeaac2a2a626c0122

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - matplotlib >=1.2.0
    - setuptools
    - netcdf4 >=1.0
    - numpy
    - scipy
    - iris >=1.8.0
    - pyhdf
    - psutil
    - pandas
    - pyhamcrest

  run:
    - python
    - matplotlib >=1.2.0
    - netcdf4 >=1.0
    - numpy
    - scipy
    - iris >=1.8.0
    - pyhdf
    - psutil
    - pandas

test:
  imports:
    - cis

  commands:
    - cis version

  requires:
    - mock
    - nose
    - pyhamcrest

about:
  home: http://www.cistools.net
  license: GNU Lesser General Public License v3 or later (LGPLv3+)
  summary: 'Community Inter-comparison Suite'

extra:
  recipe-maintainers:
     - duncanwp
